using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace ZordNest.Navigator.SourceGenerator;

[Generator]
public class RoutesRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var navigableClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ZordNest.Navigator.NavigableAttribute",
                predicate: IsClass,
                transform: GetNavigableInfo)
            .Where(info => info is not null)
            .Collect();
        context.RegisterSourceOutput(navigableClasses, GenerateCode);
    }
    
    private static bool IsClass(SyntaxNode node, CancellationToken _)
        => node is ClassDeclarationSyntax;
    
    private static NavigableInfo? GetNavigableInfo(
        GeneratorAttributeSyntaxContext context,
        CancellationToken ct)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
            return null;
        
        var attribute = context.Attributes.First();
        var key = attribute.ConstructorArguments.FirstOrDefault().Value?.ToString();

        if (key is null) return null;

        return new NavigableInfo(
            FullTypeName: classSymbol.ToDisplayString(),
            Key: key);
    }
    
    private static void GenerateCode(SourceProductionContext context, ImmutableArray<NavigableInfo?> navigableInfos)
    {
        if (navigableInfos.IsEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using ZordNest.Navigator;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace ZordNest.Navigator.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class ResolveNavigableViewModels");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection RegisterNavigableViewModels(this IServiceCollection collection)");
        sb.AppendLine("        {");

        foreach (var info in navigableInfos)
        {
            if (info is null) continue;
            sb.AppendLine($"            NavigatorViewModelStore.RegisterViewModel<global::{info.FullTypeName}>(\"{info.Key}\");");
        }

        sb.AppendLine("            return collection;"); 
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("NavigableViewModelGenerator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}


// Simple record to carry extracted info between steps
record NavigableInfo(string FullTypeName, string Key);